<#--noinspection FtlReferencesInspection,HtmlUnknownTarget-->
<script src="${pathView}/js/jquery-2.2.4.min.js"></script>
<#--noinspection FtlReferencesInspection-->
<script src="${pathView}/js/clipboard.min.js"></script>
<#--noinspection FtlReferencesInspection-->
<script src="${pathView}/js/compile.js"></script>
<#--noinspection FtlReferencesInspection-->
<script src="${pathView}/js/jquery-html5Validate-min.js"></script>
<#--noinspection FtlReferencesInspection-->
<script src="${pathView}/js/promise.min.js"></script>
<#--noinspection FtlReferencesInspection-->
<script src="${pathView}/js/template.js"></script>
<#--noinspection FtlReferencesInspection-->
<script src="${pathView}/js/common.js"></script>
<#--noinspection FtlReferencesInspection-->
<script src="${pathView}/js/jquery.common.js"></script>
<#--noinspection FtlReferencesInspection-->
<script src="${pathView}/js/project.js"></script>
<#--noinspection FtlReferencesInspection-->
<script src="${pathView}/js/enum.js"></script>
<#--noinspection FtlReferencesInspection-->
<script src="${pathView}/js/viewer-jquery.min.js"></script>